Version 3.3.0 (2012-02-03)  * allow checkhosts(1) to read hosts from stdin or on the command-line  * allow checkhosts(1) to print noping,nossh,nosshd info to stderr instead    of into separate files

diff --git a/src/checkhosts b/src/checkhosts
--- a/src/checkhosts
+++ b/src/checkhosts
@@ -51,6 +51,7 @@ TDIR="${TMPDIR:-/tmp}"
 AUTHMODE="pubkey"
 BACKGROUND='no'
 HEADLESS='yes'
+INPUT_ARGS=
 INPUT_FILES=
 OUTPUT_DIR=${TDIR}
 SCRIPT="remote.sh"
@@ -60,6 +61,7 @@ SCP_WRAPPER=".checkhosts-scp"
 CHECK_PING='yes'
 CHECK_SSHD='yes'
 HOSTNAMES_ONLY='no'
+WANT_ERRORS=
 
 ###
 ### Subroutines
@@ -71,7 +73,7 @@ HOSTNAMES_ONLY='no'
 # inputs   : none
 # outputs  : help message
 
-usage () {
+usage() {
 	cat <<EOF
 Usage: ${0##*/} [-HIPSbh] [-A authmode] [-o dir] [-r script] -f file
   -A         Specify ssh authentication mode.
@@ -98,7 +100,7 @@ EOF
 #            assumed to be an IP address
 # outputs  : appends to the three output files
 
-checkhost () {
+checkhost() {
 	local input="${1}"
 	local host="${1%% *}"
 	local ip="${1##* }"
@@ -143,7 +145,9 @@ checkhost () {
 		sshopts="${sshopts} -o NumberOfPasswordPrompts=1"
 	fi
 
-	echo "${input}" >> ${OUTFILE_CHECKED}
+	if [ -z "${WANT_ERRORS}" ]; then
+		echo "${input}" >> ${OUTFILE_CHECKED}
+	fi
 
 	if [ "${HOSTNAMES_ONLY}" = "yes" -o "${host}" = "${ip}" ]; then
 		target="${host}"
@@ -152,7 +156,11 @@ checkhost () {
 
 	if [ "${CHECK_PING}" = "yes" ]; then
 		ping -c 1 -i 1 -t 3 -q ${target} >/dev/null 2>&1 || {
-			echo ${input} >> ${OUTFILE_NOPING}
+			if [ -z "${WANT_ERRORS}" ]; then
+				echo ${input} >> ${OUTFILE_NOPING}
+			else
+				echo "Ping error: ${input}" >&2
+			fi
 			return 1
 			# NOTREACHED
 		}
@@ -160,7 +168,11 @@ checkhost () {
 
 	if [ "${CHECK_SSHD}" = "yes" ]; then
 		check_sshd ${target} || {
-			echo ${input} >> ${OUTFILE_NOSSHD}
+			if [ -z "${WANT_ERRORS}" ]; then
+				echo ${input} >> ${OUTFILE_NOSSHD}
+			else
+				echo "sshd error: ${input}" >&2
+			fi
 			return 1
 			# NOTREACHED
 		}
@@ -170,55 +182,83 @@ checkhost () {
 
 		${SCP_WRAPPER} ${sshopts} ${SSHOPTS} ${SCRIPT} ${target}:${remotefile}
 		if [ $? -gt 0 ]; then
-			echo ${input} >> ${OUTFILE_NOSSH}
+			if [ -z "${WANT_ERRORS}" ]; then
+				echo ${input} >> ${OUTFILE_NOSSH}
+			else
+				echo "ssh error: ${input}" >&2
+			fi
 			return 1
 			# NOTREACHED
 		fi
 
-		host_output=$(${SSH_WRAPPER} ${sshopts} ${SSHOPTS} ${target} "${rcmd}")
+		host_output=$(${SSH_WRAPPER} ${sshopts} ${SSHOPTS} ${target} "${rcmd} 2>/dev/null")
 	else
-		host_output=$(${SSH_WRAPPER} ${sshopts} ${SSHOPTS} ${target} "${remote_shell}" < ${SCRIPT})
+		host_output=$(${SSH_WRAPPER} ${sshopts} ${SSHOPTS} ${target} "${remote_shell}" < ${SCRIPT} 2>/dev/null)
 	fi
 
 	rval=$?
 
 	if [ ${rval} -eq 255 ]; then
-		echo ${input} >> ${OUTFILE_NOSSH}
+		if [ -z "${WANT_ERRORS}" ]; then
+			echo ${input} >> ${OUTFILE_NOSSH}
+		else
+			echo "ssh error: ${input}" >&2
+		fi
 		return 1
 		# NOTREACHED
 	elif [ ${rval} -gt 0 ]; then
 		outfile="${OUTFILE_EXITCODE}_${rval}"
 	fi
 
-	echo "${host},${ip},${host_output}" | tr '' '\n' >> ${outfile}
+	if [ -z "${WANT_ERRORS}" ]; then
+		echo "${host},${ip},${host_output}" | tr '' '\n' >> ${outfile}
+	fi
 }
 
-# function : process_input_files
-# purpose  : work of the lines in all input files
+# function : process_input
+# purpose  : work of the lines in all input files, arguments or stdin
 # usage    : process_input_files
 # inputs   : none, operates on global INPUT_FILES
 # outputs  : none
 
-process_input_files () {
+process_input() {
+	local file line
 
-	local file
+	# items given as arguments first...
+	for line in ${INPUT_ARGS}; do
+		checkhost "$line"
+	done
 
+	# next, any input files
 	for file in ${INPUT_FILES}; do
-		if [ -r "${file}" ]; then
-			local readonly tmpf=$(mktemp ${TDIR}/checkhosts.$$.XXXXXX)
-			grep -v "^#" ${file} > ${tmpf}
-			oIFS=${IFS}
-			IFS='
+		oIFS=${IFS}
+		# careful: there's a newline in quotes
+		IFS='
 '
-			for line in $(cat ${tmpf}); do
+		if [ -r "${file}" ]; then
+			for line in $(grep -v "^#" ${file}); do
 				IFS=${oIFS}
 				checkhost "${line}"
 			done
-			rm ${tmpf}
 		else
 			echo "Cannot read ${file}." >&2
 		fi
 	done
+
+	# if we haven't done anything, then we try to read input from
+	# stdin
+	if [ -z "${INPUT_FILES}" -a -z "${INPUT_ARGS}" ]; then
+		oIFS=${IFS}
+		# careful: there's a newline in quotes
+		IFS='
+'
+		while read line; do
+			IFS=${oIFS}
+			checkhost "${line}"
+		done
+	fi
+
+
 }
 
 # function : check_sshd
@@ -282,7 +322,7 @@ wrap_ssh() {
 ###
 
 main() {
-	while getopts 'A:HIPSbf:ho:r:' opt; do
+	while getopts 'A:HIPSbef:ho:r:' opt; do
 		case ${opt} in
 			A)
 				AUTHMODE="${OPTARG}"
@@ -301,6 +341,9 @@ main() {
 			;;
 			b)
 				BACKGROUND='yes'
+			;;
+			e)
+				WANT_ERRORS='yes'
 			;;
 			f)
 				INPUT_FILES="${INPUT_FILES} ${OPTARG}"
@@ -330,11 +373,7 @@ main() {
 	done
 	shift $(($OPTIND - 1))
 
-	if [ -z "${INPUT_FILES}" -a $# -lt 1 ]; then
-		usage
-		exit 1
-		# NOTREACHED
-	fi
+	INPUT_ARGS="$@"
 
 	if [ ! -r ${SCRIPT} ]; then
 		echo "Unable to read script \"${SCRIPT}\"." >&2
@@ -351,7 +390,7 @@ main() {
 
 	wrap_ssh
 
-	process_input_files
+	process_input
 
 	return 0
 }
